---
driver:
  name: docker
  privileged: true
  use_sudo: false
provisioner:
  name: chef_solo
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7

    driver:

      platform: rhel

      run_command: /usr/lib/systemd/systemd

suites:
  - name: default
    run_list:
      - recipe[test::default]
    verifier:
      inspec_tests:
       - test/smoke/default
    attributes:
